Currency max length defaults
django-money/django-money pull request #614
Opened 2021-04-24 07:24 UTC by ayushin

Attention - this affects initial migration, so CURRENCY_TICKER_MAX_LENGTH (default 3) can't be changed afterwards without creating a new migration

2021-04-24 07:25 UTC, ayushin commented
This PR works for us

https://github.com/django-money/django-money/pull/614

2021-04-24 13:12 UTC, benjaoming requested changes
Changes look good and shouldn't affect existing deployments. I don't understand why it's called "Currency Ticker"? It's not a term that I'm familiar with. Wouldn't we normally call this a "currency code"?

It would be nice to have a comment or some kind of documentation that this setting cannot be changed without manually creating database migrations.

2021-04-24 13:35 UTC, ayushin commented
I've changed it to CURRENCY_CODE I guess you are right, it is more suiting for the module naming.

Also added a note in the README

2021-04-24 15:08 UTC, benjaoming approved these changes
Thanks for addressing the feedback @ayushin - If you can add a release note for this, too, that would be sweet. Otherwise LGTM :+1:

2021-04-24 15:25 UTC, Stranger6667 approved these changes

2021-04-24 23:13 UTC, benjaoming commented
Hi @ayushin

You can fix the lint error with something like this:

```
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

2021-04-27 21:07 UTC, benjaoming approved these changes
LGTM :rocket:

2021-04-28 06:15 UTC, merged